### ISSUE TITLE
windows desktop program can't run after publish

### ISSUE THREAD

**Issue by hubo0831** [nulastudio/NetBeauty2#31]
安装了nulastudio.NetBeauty 2.0.0-beta.4，在win10 64位系统.net core 3.1上测试发布，发布的程序不能运行，调试运行报IOException，请问如何解决？

**Comment by hubo0831** [comment]
使用的框架依赖方式

**Comment by liesauer** [comment]
能创建一个测试案例吗？

**Comment by liesauer** [comment]
不然不好远程排查问题
