### ISSUE TITLE
WinUI3 and WASDK Support

### ISSUE THREAD

**Issue by ghost1372** [nulastudio/NetBeauty2#32]
is there any support for WASDK/WinUI 3?

**Comment by ghost1372** [comment]
tnx, you can download sample project

[App28.zip](https://github.com/nulastudio/NetBeauty2/files/8804442/App28.zip)

note:
- WinUI 3 app can be published as UnPackaged and Packaged (MSIX)
- Currently it is not possible to publish as a single exe file for unpackaged (blocked by wasdk bug)
- NetBeauty must be run in unpackaged mode
- WindowsAppSDK package can also be installed in WPF/Winform so mybe you may need to make changes to other platforms as well

I've been testing it now and it needs a little tweaking. Not all files and folders are transferred
![image](https://user-images.githubusercontent.com/9213496/171157767-cf5af3c7-552b-450d-9645-c17a2ace0204.png)
![image](https://user-images.githubusercontent.com/9213496/171157834-0f402c12-7fef-414e-9399-1399335750d5.png)

**Comment by liesauer** [comment]
wasdk dlls are really a mess, it's extremely hard to analyze which dll should be moved. and lots of core wasdk dlls are loaded from incomprehensible paths, not the app base. so no winui3 and wasdk support for now.
