### ISSUE TITLE
VirusTotal flags the nbeauty2.exe as malicious

### ISSUE THREAD

**Issue by MariusMichelPrimes** [nulastudio/NetBeauty2#35]
So what is going on here? Are those false flags or is there malicious code in the binary release of this tool?

**Comment by liesauer** [comment]
it must be misdeclaration, i have tried others scan systems, some of them report no rhyme or reason network connections.

[x86 by virustotal](https://www.virustotal.com/gui/file/2c00e88b4446b34e99b8a29dc3d5bd29e07761f5baaa066daf1aeb8ea4fd26f1/behavior)
![x86](https://user-images.githubusercontent.com/8676741/176087824-8bbd556d-2528-42b2-bfb6-2953df8f8e8c.png)

<hr />

[x64 by virustotal](https://www.virustotal.com/gui/file/a2e40c77297601905222430512428f3b9dbcb4a97f722cc8fea5720bffc78ef4/behavior)
![x64](https://user-images.githubusercontent.com/8676741/176087839-ddefa923-5879-4e0d-9056-3fc80055b15b.png)

<hr />

[maldun](https://www.maldun.com/analysis/YXNkZmRzZmFkc2Y2OTY5OTZkc2Zhc2RmYXNkZg==/)
![image](https://user-images.githubusercontent.com/8676741/176088041-c32b1497-0334-485b-aeb3-fa78d0905c65.png)

<hr />

[qianxin](https://sandbox.ti.qianxin.com/sandbox/page/detail?type=file&id=AYGoP_xOCf0-QUp-0-TQ)
![image](https://user-images.githubusercontent.com/8676741/176088185-74707d51-bbda-481f-b4cd-decc0f3f84c2.png)

<hr />

[threatbook](https://s.threatbook.cn/report/file/a2e40c77297601905222430512428f3b9dbcb4a97f722cc8fea5720bffc78ef4)
![image](https://user-images.githubusercontent.com/8676741/176088281-3dff1a74-6449-4465-b38c-ef4b077e841d.png)

**Comment by MariusMichelPrimes** [comment]
I read somewhere, that GO progams under windows sometimes get falsely flagged by some anti virus tools. Maybe that is the problem here.

**Comment by liesauer** [comment]
i think so too
