### ISSUE TITLE
Error: cannot find a compatible rid for win-x64

### ISSUE THREAD

**Issue by d3n1s47** [nulastudio/NetBeauty2#39]
I am getting this error on a .NET 6 project that is composed of itself and 3 class librairies.  Can you point me in the right direction to get this to work? It was working when every project was set to x86 for compatibility reasons with the Excel driver but now I get this error no matter what I do!

This error shows up when using the CLI tool or the nuget package within the project.

**Comment by d3n1s47** [comment]
Note that this happens immediately after the "patching hostfxr" step.  all 3 class libraries are set to "any CPU" and the main project is set to win-x64 in the publish profile's runtime identifier.

**Comment by liesauer** [comment]
try setting `<BeautyLogLevel>Info</BeautyLogLevel>`, and please paste the log, a public repo to test will be the best, but the log is also ok.

**Comment by liesauer** [comment]
it looks like it is caused by the multi project structure, can you upload a reproducible repo? the log may help nothing. a compilable but not runnable testcase is ok too, you can delete all sensitive data and code, but make sure that it is compilable.

**Comment by d3n1s47** [comment]
it worked as a 4 project structure before I switched everything from x86 to any cpu.  Now it does not work even if I revert back to the same configuration as before.  The multi project structure is definitely not the problem.

**Comment by liesauer** [comment]
need more infos
