### ISSUE TITLE
Feature request for patch when debug

### ISSUE THREAD

**Issue by Dynesshely** [nulastudio/NetBeauty2#40]
I noticed that this only run when doing `dotnet publish` when trying mode of adding `PropertyGroup` in .csproj, so can NetBeauty2 run when debuging?

**Comment by liesauer** [comment]
it has the chance to do so since NetBeauty2 can run in `FDD` and `FDE` mode now.

**Comment by Dynesshely** [comment]
Tnx.
I tried copy the suggested .csproj into my project, and NetBeauty2 works perfectly when publishing.
So how can I force NetBeauty2 patch in debug mode just by writing in .csproj ?
Tnx.

**Comment by liesauer** [comment]
try adding the following config to `.csproj` with latest NetBeauty2 `v2.0.0.0-beta.7`
```xml
<BeautyOnPublishOnly>False</BeautyOnPublishOnly>
```

**Comment by Dynesshely** [comment]
Tnx
