### ISSUE TITLE
Weird artifact error

### ISSUE THREAD

**Issue by the-black-wolf** [nulastudio/NetBeauty2#45]
Getting this from publish:

```
1>------ Publish started: Project: RevenueGovernance, Configuration: Release Any CPU ------
1>Determining projects to restore...
1>All projects are up-to-date for restore.
1>RevenueGovernance -> C:\projects\RevenueGovernance\RevenueGovernance\bin\Release\net7.0-windows\win-x64\RevenueGovernance.dll
1>RevenueGovernance -> C:\projects\RevenueGovernance\RevenueGovernance\bin\Release\net7.0-windows\win-x64\publish\
1>"C:\Users\Administrator\.nuget\packages\nulastudio.netcorebeauty\1.2.9.3\targets\../tools/win-x86/ncbeauty.exe"   --loglevel Info     "C:\projects\RevenueGovernance\RevenueGovernance\bin\Release\net7.0-windows\win-x64\publish\/." ./libraries 
1>running ncbeauty...
1>checking runtime.*.json version...
1>runtime.compatibility.json no need to update
1>runtime.supported.json no need to update
1>incomplete fxr info [v/] found in deps.json: C:/projects/RevenueGovernance/RevenueGovernance/bin/Release/net7.0-windows/win-x64/publish/RevenueGovernance.deps.json
1>Artifact does not exist. /
```

It does not look like a standard missing artifact issue. 

.net core 7 in case its important. win70-windows/win-x64

**Comment by liesauer** [comment]
looks like it fails to extract the fxr info, please upload your `deps.json` and `runtimeconfig.json`.

**Comment by n0099** [comment]
I've encounter this issue too while publishing with following profile:
![image](https://user-images.githubusercontent.com/13030387/204090731-3cab32f9-e8b2-4197-a5ba-752c121e2462.png)
```
2>"C:\Users\n0099\.nuget\packages\nulastudio.netcorebeauty\1.2.9.3\targets\../tools/win-x86/ncbeauty.exe"   --loglevel Detail     "G:\n0099.dev\tbm\dev\crawler\bin\Release\net6.0\publish\/." ./libs 
2>incomplete fxr info [v/] found in deps.json: G:/n0099.dev/tbm/dev/crawler/bin/Release/net6.0/publish/tbm.Crawler.deps.json
2>Artifact does not exist. /
2>The command ""C:\Users\n0099\.nuget\packages\nulastudio.netcorebeauty\1.2.9.3\targets\../tools/win-x86/ncbeauty.exe"   --loglevel Detail     "G:\n0099.dev\tbm\dev\crawler\bin\Release\net6.0\publish\/." ./libs " exited with code 1.
```
here's my `deps.json`: [tbm.Crawler.deps.zip](https://github.com/nulastudio/NetBeauty2/files/10096318/tbm.Crawler.deps.zip)

**Comment by liesauer** [comment]
`FDD` and `FDE` only supported by NetBeauty2, so you guys need update to the lastest `NetBeauty v2.0+`.
@the-black-wolf @n0099

**Comment by n0099** [comment]
What's the NuGet package name of 2.0?
searching `nulastudio.NetBeauty` only gives me two package with different name but same version and author:
![image](https://user-images.githubusercontent.com/13030387/204127370-4493998f-e124-4c86-a28c-a95fa79a6346.png)

**Comment by liesauer** [comment]
`NetCoreBeauty` only supports `.NET Core` and `SCD` mode, `ncbeauty` is the cli version of `NetCoreBeauty`.
`NetBeauty` supports `.NET Core` and `.Net Fx`(unfinished) and all deployment mode.
