### ISSUE TITLE
编译 debug 是无效的对吧?

### ISSUE THREAD

**Issue by sgf** [nulastudio/NetBeauty2#46]
不是publish 仅仅是 编译.
debug的时候 dll什么的太多,找个文件挺费劲的.

**Comment by liesauer** [comment]
`v2.0.0.0-beta.7`版本或以上已经支持在build的时候使用，参见此issue，#40。

**Comment by sgf** [comment]
very powerful! tks

**Comment by sgf** [comment]
直接F5 的情况下,还是一堆文件.

**Comment by liesauer** [comment]
在项目没有改动的情况下，F5是不编译项目的，这种情况下是触发不了的，可以试下清理项目，后续按理说是能保持beauty的。

1. 第一次运行，必然build，进行beauty
2. 后续改了代码，F5正常触发build，进行beauty
3. 不改代码，F5直接运行，不触发build，不进行beauty，但文件夹结构理论上应该与上一次的一样
