### ISSUE TITLE
Could not find or load a specific file System.Configuration.ConfigurationManager.dll

### ISSUE THREAD

**Issue by sgf** [nulastudio/NetBeauty2#50]
环境: win10 x64 , .net6-windows winform项目

System.Reflection.ReflectionTypeLoadException:“Unable to load one or more of the requested types.
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)”

该错误发生在 启动项目 assembly.GetTypes 调用的时候.

使用`<DisableBeauty>True</DisableBeauty>` 后发生:
 bloader.dll 找不到或者加载不了的类似错误. 但是这个dll始终都在那
保持禁用 NetBeauty2,全部重新生成主项目后恢复正常(没有任何报错)

本问题怀疑和另一个issue 有关系(即自动给加载了不同版本了的dll导致的错误)

**Comment by liesauer** [comment]
这个问题与 #48 是类似的，不知道为什么使用`AssemblyLoadContext.LoadFromAssemblyPath`来加载`System.Configuration.ConfigurationManager.dll`是加载不了的

**Comment by liesauer** [comment]
此问题已在 [`v2.1.3.0-beta.1`](https://github.com/nulastudio/NetBeauty2/releases/tag/v2.1.3.0-beta.1) 解决。

**Comment by sgf** [comment]
> 此问题已在 [`v2.1.3.0-beta.1`](https://github.com/nulastudio/NetBeauty2/releases/tag/v2.1.3.0-beta.1) 解决。

![image](https://user-images.githubusercontent.com/2557696/236608824-25c40d06-0ac1-4e1f-81dc-03b1e04a026b.png)


System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
  Source=System.Private.CoreLib
  StackTrace:
   在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   在 System.Reflection.Assembly.GetTypes()
   在 Acctrue.PrintApp.Infrastructure.AsmTypesCache.<>c__DisplayClass0_1.<AddOrUpdate>b__1(Assembly asm) 在 E:\Work\Git\Print.YuHong\PrinterApp\PrintApp.Infrastructure\DI\AsmTypesCache.cs 中: 第 43 行
   在 System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   在 Acctrue.PrintApp.Infrastructure.AsmTypesCache.<>c__DisplayClass0_0.<AddOrUpdate>b__0(Assembly assembly) 在 E:\Work\Git\Print.YuHong\PrinterApp\PrintApp.Infrastructure\DI\AsmTypesCache.cs 中: 第 40 行
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)


右键项目清理后，重新生成，并安装了最新的 [v2.1.3.0-beta.1]( https://github.com/nulastudio/NetBeauty2/releases/tag/v2.1.3.0-beta.1)，但 问题依旧。

**Comment by liesauer** [comment]
能提供一份demo用来测试嘛，看图的话，`asm`都拿到了，`GetTypes`就不应该会报才对。

**Comment by sgf** [comment]
> 能提供一份demo用来测试嘛，看图的话，`asm`都拿到了，`GetTypes`就不应该会报才对。

对了我补充说一个事情，我用了两个STA线程。

**Comment by sgf** [comment]
> 能提供一份demo用来测试嘛，看图的话，`asm`都拿到了，`GetTypes`就不应该会报才对。

我尝试过一次，但是简单的例子确实不太好模拟。约个时间，远程看看？

**Comment by sgf** [comment]
今天尝试 将.net sdk切换到7.0 后该问题得到解决。这说明之前不知道什么原因，应用程序虽然是.net 6.0的但是却无意间引用了7.0的dll。这导致了报错问题。虽然没有使用NetBeauty2的时候没有报错，但是使用了NetBeauty2的时候就报了错。不过无所谓，解决了问题就行。
