### ISSUE TITLE
Visual Studio publish profile doesn't trigger NetBeauty

### ISSUE THREAD

**Issue by GlodenBoy** [nulastudio/NetBeauty2#51]
Unable to trigger components after upgrading from 2.0.0.0-beta.7 to 2.1.1,

Configuration file:
![image](https://user-images.githubusercontent.com/2329528/226816964-f34dae35-e8e9-48b3-a0e8-ba3229be9a6d.png)

![image](https://user-images.githubusercontent.com/2329528/226818178-949ffedd-7572-40d6-9a1f-725479305e5d.png)

After upgrading to the latest version, files are not organized when publishing.

There is no problem before upgrading

Only previews are recognized

**Comment by liesauer** [comment]
can you post a testcase? so i can have a deep look.

**Comment by GlodenBoy** [comment]
> can you post a testcase? so i can have a deep look.

刚发现老哥是 中国人，翻译有点累，整个QQ远程求助下，扣以吗？

**Comment by liesauer** [comment]
现在的话没有空，最多只能等晚上，如果能传一个案例上来，我抽空也能看看，如果不是更新后的代码问题也能比较快解决。

**Comment by GlodenBoy** [comment]
> 现在的话没有空，最多只能等晚上，如果能传一个案例上来，我抽空也能看看，如果不是更新后的代码问题也能比较快解决。

[WpfApp4.zip](https://github.com/nulastudio/NetBeauty2/files/11037251/WpfApp4.zip)
做了一个wpf例子，也是这样的，

**Comment by liesauer** [comment]
暂时可这么解决：

## 第一种方法
1. `<BeautyOnPublishOnly>False</BeautyOnPublishOnly>`
2. 重新发布
3. 此时`bin/Release`下的文件确实是没处理到的（BUG）
4. 但是`bin/x64/Release/net6.0-windows/win-x64`下的文件是正常处理了的，可以先用这一份程序

## 第二种方法
1. 使用命令行发布，`dotnet publish -c Release -r win-x64`

**Comment by liesauer** [comment]
这个问题的核心原因是因为VS的发布用了自己的一套命令和编译流程，而不是像我们常规的`dotnet publish`一样，导致`NetBeauty`无法判断正在运行的到底是build还是publish。

**Comment by GlodenBoy** [comment]
> 这个问题的核心原因是因为VS的发布用了自己的一套命令和编译流程，而不是像我们常规的`dotnet publish`一样，导致`NetBeauty`无法判断正在运行的到底是build还是publish。

OK ，现在是用的x64

**Comment by GlodenBoy** [comment]
> 1. <BeautyOnPublishOnly>False</BeautyOnPublishOnly>

第一种方法改成<BeautyOnPublishOnly>False</BeautyOnPublishOnly>  输出里触发了组件，但是实际文件夹里没有挪

**Comment by liesauer** [comment]
![image](https://user-images.githubusercontent.com/8676741/226846360-c19b4959-2d9c-4153-bd80-74d24601b655.png)

其实`x64`下的是有处理的，但是后面貌似又被复制了一份完整的进去

我这边测试到，发布一共触发了三次编译
![image](https://user-images.githubusercontent.com/8676741/226846844-0792a729-e4c9-4661-bb50-fd7e2930fca6.png)

**Comment by liesauer** [comment]
https://github.com/dotnet/msbuild/issues/8585

**Comment by GlodenBoy** [comment]
> [dotnet/msbuild#8585](https://github.com/dotnet/msbuild/issues/8585)

![image](https://user-images.githubusercontent.com/2329528/226856251-11028b72-0581-4031-8bc5-033ba596621f.png)

x64是可以的，因为我是这样配置的，结果 在我的目标位置 是失败的，只有返回到x64目录去找 是OK的， 确实会重复好几次，不过现在看X64是正确的

**Comment by liesauer** [comment]
这个行为貌似是不定的

1. 清理`bin`目录
2. 发布
3. 重复发布...

就会发现会有一份重复的dll在那了，前几次发布（我这边稳定前两次）确实是正常的

**Comment by GlodenBoy** [comment]
> 这个行为貌似是不定的
> 
> 1. 清理`bin`目录
> 2. 发布
> 3. 重复发布...
> 
> 就会发现会有一份重复的dll在那了，前几次发布（我这边稳定前两次）确实是正常的

很奇怪为啥 老的 2.0.0.0-beta.7 是正常的？

**Comment by liesauer** [comment]
你好，这个问题已在最新的`v2.1.2`版本修复。
