### ISSUE TITLE
能够实现比较极端的模式么

### ISSUE THREAD

**Issue by sgf** [nulastudio/NetBeauty2#52]
比如这种：

![image](https://user-images.githubusercontent.com/2557696/236609609-6c61a6e3-a1e5-4f2e-ba83-7b940cc0e597.png)

**Comment by sgf** [comment]
外部就一个exe。然后不同版本的Exe加载不同版本的文件夹。

**Comment by liesauer** [comment]
我之前也有想过这种结构，但是目前只是理论阶段，有两种理论实现方式。

第一种：独立部署 + [`AppHostPatcher`](https://github.com/dnSpy/dnSpy/tree/master/Build/AppHostPatcher) + `NetBeauty`

```text
├── v1.0
│   ├── hostfxr.dll;...
│   ├── nbloader.dll
│   ├── app.deps.json
│   ├── app.dll
│   ├── app.runtimeconfig.json
│   └── ...
│
│
├── v2.0
│   ├── hostfxr.dll;...
│   ├── nbloader.dll
│   ├── app.deps.json
│   ├── app.dll
│   ├── app.runtimeconfig.json
│   └── ...
│
├── app_v1.0.exe                - apphost(will load dll from `v1.0`)
└── app_v2.0.exe                - apphost(will load dll from `v2.0`)
```

第二种：独立部署 + 魔改SingleFile（部分打包） + `NetBeauty`
文件夹结构与第一种类似，只不过可能会多出几个文件（单文件部署需要额外的依赖才能解压，这些文件都是不能够移动的），可能会与`nbloader`冲突。

第一种方案落地成功率是比较高的。

**Comment by sgf** [comment]
> 我之前也有想过这种结构，但是目前只是理论阶段，有两种理论实现方式。
> 
> 第一种：独立部署 + [`AppHostPatcher`](https://github.com/dnSpy/dnSpy/tree/master/Build/AppHostPatcher) + `NetBeauty`
> 
> ```
> ├── v1.0
> │   ├── hostfxr.dll;...
> │   ├── nbloader.dll
> │   ├── app.deps.json
> │   ├── app.dll
> │   ├── app.runtimeconfig.json
> │   └── ...
> │
> │
> ├── v2.0
> │   ├── hostfxr.dll;...
> │   ├── nbloader.dll
> │   ├── app.deps.json
> │   ├── app.dll
> │   ├── app.runtimeconfig.json
> │   └── ...
> │
> ├── app_v1.0.exe                - apphost(will load dll from `v1.0`)
> └── app_v2.0.exe                - apphost(will load dll from `v2.0`)
> ```
> 
> 第二种：独立部署 + 魔改SingleFile（部分打包） + `NetBeauty` 文件夹结构与第一种类似，只不过可能会多出几个文件（单文件部署需要额外的依赖才能解压，这些文件都是不能够移动的），可能会与`nbloader`冲突。
> 
> 第一种方案落地成功率是比较高的。

好想法。

单文件本来是挺好的，但可惜的是.net的单文件做得不彻底。

**Comment by liesauer** [comment]
第一种方案已经能够实现了，[https://github.com/nulastudio/NetBeauty2#customize-apphost](https://github.com/nulastudio/NetBeauty2#customize-apphost)。

**Comment by liesauer** [comment]
最终的效果如下，文件夹的名字可任意修改：

![image](https://github.com/nulastudio/NetBeauty2/assets/8676741/d5446148-41ee-4a25-9454-db5c8cbd5130)

**Comment by sgf** [comment]
> Member
老哥牛逼啊。这个文件夹名字可以任意修改，意思是可以做 V1 V2 那种结构了？

**Comment by liesauer** [comment]
是的，名字是任意的，参考共享运行时那个demo，目录就是发布的时候自定义的
