### ISSUE TITLE
Roll forward global tools

### ISSUE THREAD

**Issue by Ellpeck** [nulastudio/NetBeauty2#53]
Hi, thanks so much again for these fabulous tools! In case you don't remember, I use NetCoreBeauty v1 as part of my tool [GameBundle](https://github.com/Ellpeck/GameBundle).

Unfortunately, all of the global tools attached to this project don't have the `RollForward` directive, which means that users have to have the exact version of .NET installed that the tool was built with to use it. In most cases, this is unnecessary, as newer versions are usually backwards-compatible for tool execution.

I recently [updated](https://github.com/Ellpeck/GameBundle/commit/058f516502a08c62954fd3b56ea3562ad0b7208e) GameBundle to include this feature, but essentially all you have to do is add this to your project file:
```xml
<RollForward>Major</RollForward>
```

For more info, I used the official documentation from here: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#rollforward

Thanks so much, and I hope you consider adding this directive to the v1 global tool as well!

**Comment by liesauer** [comment]
`--roll-forward` option is added to both v1 and v2.

**Comment by Ellpeck** [comment]
Thanks so much for adding this!

Unfortunately, I don't think you understood what my request was? I was asking for the NetBeauty global tools (specifically https://www.nuget.org/packages/nulastudio.ncbeauty and https://www.nuget.org/packages/nulastudio.nbeauty) to have the `RollForward` directive added to them, so that people using your tools don't have to have outdated versions of .NET installed.

**Comment by liesauer** [comment]
oh, you mean the global tools `ncbeauty` and `nbeauty` themself?

**Comment by Ellpeck** [comment]
Yes! Currently, to use them, you have to have .NET Core 2.1 installed. As I said in my original post, having the exact matching .NET version installed is almost never necessary for tool execution, so this is likely an unnecessary requirement.

**Comment by liesauer** [comment]
the global tool has been updated, i tested it, it works very well, thanks for the advice.
