### ISSUE TITLE
XamlParseException in Version 2.1.3.3

### ISSUE THREAD

**Issue by BornToBeRoot** [nulastudio/NetBeauty2#54]
Hi,

i upgraded from version 2.1.2.1 to 2.1.3.3 and now i get an XamlParseException when starting the app.

![image](https://github.com/nulastudio/NetBeauty2/assets/16019165/543e7c93-e5cc-4d02-9086-b7d899689d83)

Edit: Sample project https://github.com/BornToBeRoot/NETworkManager

**Comment by liesauer** [comment]
https://github.com/dotnet/runtime/issues/86756

**Comment by liesauer** [comment]
Fixed in 8c0ac96

**Comment by BornToBeRoot** [comment]
@liesauer thanks. I will test this later.

**Comment by BornToBeRoot** [comment]
@liesauer seems to work for me! Thanks again!
