### ISSUE TITLE
System.IO.Packaging.dll not moved to libraries after publish

### ISSUE THREAD

**Issue by julienGrd** [nulastudio/NetBeauty2#55]
Hello guys, and thanks for this usefull library.

I use it for an asp .net core 7.0 project, it work perfectly after publish, but i notice one dll of my project is not move to the libraries folder, System.IO.Packaging.dll.

Do yo have any idea why ?

thanks !

**Comment by liesauer** [comment]
some special dlls are expected as they are designed to not be moved, this depends on:
1. Deployment Mode
2. Project Framework(ASP .NET Core or WPF, etc.)
3. Shared Runtime Mode
4. Use or not use patch

**Comment by liesauer** [comment]
you can post your config and compiled app so i can double check if it works as excepted for your project.

**Comment by julienGrd** [comment]
I can't really post the app because its a commercial app and the source code is private, but this the configuration :
 asp.net core 7.0 project, running a blazor server app, the deployment mode is FileSystem, not self contained, runtime identifier win-64, i don't know if you need more informations ? if needed i can try create a repro project, let me know.

**Comment by liesauer** [comment]
the behavior is highly depends on `*.deps.json`, you can just upload the `*.deps.json` and `*.runtimeconfig.json`, they don't have any sensitive contents and safe to upload.

**Comment by julienGrd** [comment]
hello, does there any update on this ?

**Comment by liesauer** [comment]
can you try create a minimum reproductable project?

**Comment by julienGrd** [comment]
It seem since .net8.0 we "lost" this dependency (but without impact on our app), so the problem solve by itself, im unable to reproduce the problem, i close this issue, but thanks for your help
````
"DocumentFormat.OpenXml/2.20.0": {
        "dependencies": {
          "System.IO.Packaging": "4.7.0"
        },
        "runtime": {}
      },
````

**Comment by liesauer** [comment]
please feel free to reopen if issue still exists.
