### ISSUE TITLE
Is it normal the pdb are not moved to the library folder ?

### ISSUE THREAD

**Issue by julienGrd** [nulastudio/NetBeauty2#57]
Hello guys, and thanks for this library.
it works greate except the pdb which stay at the root (yes i want to publish the pdf in release mode to have line number in case of exceptions).

Is it normal ? can it be configured ?

thanks !

**Comment by liesauer** [comment]
pdb should stay with it's dll. can you post a demo repo/bin so i can see what is going on?

**Comment by julienGrd** [comment]
yes you can repro with this project : https://github.com/julienGrd/BlazorAppTestNetBeautyWithPdb, i use Visual Studio Community 2022 17.8 Preview 2.0. To reproduce 
- right click, publish on the server project
- go to the publish folder, you will see ClassLibrary1.dll and ClassLibrary2.dll in the libraries subfolder but ClassLibrary1.pdb and ClassLibrary2.pdb are still in the root

**Comment by liesauer** [comment]
fixed in [v2.1.4.1](https://github.com/nulastudio/NetBeauty2/releases/tag/v2.1.4.1)
