### ISSUE TITLE
BeautySharedRuntimeMode True throws a exception

### ISSUE THREAD

**Issue by Diddlik** [nulastudio/NetBeauty2#58]
If I use NetBeauty with BeautySharedRuntimeMode it works fine, If I switch BeautySharedRuntimeMode to true it throws on application start an exception.

It is an WPF Application. It includes 6 subprojects.

"Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.":"Microsoft.Extensions.DependencyInjection.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"} | System.IO.FileNotFoundException

**Comment by liesauer** [comment]
can you share a minimal reproductable demo?
