### ISSUE TITLE
Any plans on supporting osx-arm64

### ISSUE THREAD

**Issue by arosolino** [nulastudio/NetBeauty2#61]
Hi,

Do you have any plans on supporting osx-arm64 builds?

Thanks!

**Comment by liesauer** [comment]
i can't tell, currently i am running macos on VirtualBox, and it's 10x slower then the real machine without graphics card, i can try setting up the corss-build environment these days, and will let you know if there is any progress.

**Comment by liesauer** [comment]
osx-arm64 has been supported in [v2.1.4.2](https://github.com/nulastudio/NetBeauty2/releases/tag/v2.1.4.2)

to test if it works
1. download [.net sdk 6.0.418](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)(must exactly this version, only v6.0.26 hostfxr for testing)
2. create a simple console project
3. install NetBeauty2 v2.1.4.2
4. build with `dotnet publish -r osx-arm64`
5. run the app on a apple silicon machine

let me know if it works
