### ISSUE TITLE
[Feature] Support .NET MAUI Windows export

### ISSUE THREAD

**Issue by AndreasReitberger** [nulastudio/NetBeauty2#62]
Are there any plans that the non-package export for net maui will be supported as well?
https://learn.microsoft.com/de-de/dotnet/maui/windows/deployment/publish-unpackaged-cli?view=net-maui-8.0

**Comment by liesauer** [comment]
In fact, I started researching on adapting WASDK a long time ago, but unfortunately, I couldn't make it happen. See https://github.com/nulastudio/NetBeauty2/issues/32#issuecomment-1441916031 for the main reason.

**Comment by AndreasReitberger** [comment]
Thanks for the clarification on this.
