### ISSUE TITLE
三方组件没有引用到环境dll

### ISSUE THREAD

**Issue by GlodenBoy** [nulastudio/NetBeauty2#66]
wpf里使用了 使用 AutoUpdater.NET.dll 组件

使用独立打包一起打包， 并且使用了 NetBeauty2 美化目录

触发更新后，会弹出官网的提示缺少 .net6 环境

**Comment by liesauer** [comment]
能否提供一个可复现的demo呢？

**Comment by GlodenBoy** [comment]
> 能否提供一个可复现的demo呢？

demo可能需要部署一个http ，挺麻烦的，我先反复美化和不美化尝试一下 找下原因，看看是https://github.com/ravibpatel/AutoUpdater.NET升级组件问题还是什么原因，

**Comment by liesauer** [comment]
获取更新这个倒是简单，随便开个服务，放个xml就行

**Comment by GlodenBoy** [comment]
抱歉，我知道了，是这个升级组件的原因，它会解压到系统目录并且启动，但是系统目录下没有环境依赖。
