### ISSUE TITLE
Using NetBeauty together with Visual Studio Installer Projects

### ISSUE THREAD

**Issue by f4l0** [nulastudio/NetBeauty2#70]
Hey guys,

NetBeauty works great when building the application from VS. To deliver the app, I like to use the VS Installer Project. 
The installer uses the publish item to gather the files from the project. However, it looks like, that the installer uses the not beautyfied version where all the libs are placed in the root folder

Anyone has an idea?

**Comment by f4l0** [comment]
I found a solution. I added a lib folder to the installation folder and used a lot of filters to control which file goes where...

**Comment by liesauer** [comment]
> I found a solution. I added a lib folder to the installation folder and used a lot of filters to control which file goes where...

can you upload a demo to show us how to achieve this? and it would be great if i put it into NetBeauty2 as example project.

**Comment by f4l0** [comment]
Yeah sure, where should I upload the test solution?

**Comment by liesauer** [comment]
in this issue is fine.

**Comment by f4l0** [comment]
Not cleaned up yet... But I hope you figure it out...
[NetBeauty2InstallerDemo.zip](https://github.com/user-attachments/files/17458279/NetBeauty2InstallerDemo.zip)

**Comment by liesauer** [comment]
yeah, don't worry about this
