### ISSUE TITLE
某些应用使用此插件后会导致无法启动

### ISSUE THREAD

**Issue by YIYuNCU** [nulastudio/NetBeauty2#71]
# 问题描述
1. 在使用本插件编译开源项目VPET(github)会导致应用编译后无法启动，提示缺少文件
2. 在Visual Studio全局使用后无法取消使用(至少在readme里面未给出)
![屏幕截图 2024-11-02 154052](https://github.com/user-attachments/assets/54543990-fed2-4c57-ab67-b9267122f508)

**Comment by liesauer** [comment]
> 2. 在Visual Studio全局使用后无法取消使用(至少在readme里面未给出)

这样子就能关闭，关闭后需要清理解决方案再编译，因为VS是增量编译的形式，每次开关后文件都会乱掉的。
```xml
<DisableBeauty>True</DisableBeauty>
```

**Comment by liesauer** [comment]
> 1. 在使用本插件编译开源项目VPET(github)会导致应用编译后无法启动，提示缺少文件

经测试，不管是Build还是Publish，我这边都是顺利运行的，全默认配置
![image](https://github.com/user-attachments/assets/60dae654-2d29-4de0-969e-bf942f7ff413)

**Comment by liesauer** [comment]
你是在VS里面直接调试运行嘛？

**Comment by liesauer** [comment]
我这边`dotnet publish`测试也是没问题的
![image](https://github.com/user-attachments/assets/bff1ebe1-1851-4497-916f-d45964ddf361)

**Comment by YIYuNCU** [comment]
这个命令窗口不应该是编译后出现的内容，而且游戏本体和这个窗口绑定起来了，这个窗口关了游戏也会被关闭

**Comment by liesauer** [comment]
> 而且补上Core模组后也不能正常运行

关于这个问题，是这么造成的
1. NetBeauty2会把所有能够移动的dll放在libraries下，其中包括了VPet-Simulator.Core.dll、VPet-Simulator.Windows.Interface.dll
2. 根据VPet的提示运行mklink.bat，mod会复制一份到程序根目录
3. 但是程序实际运行时，却是在libraries\mod中读取，也就是跟随了VPet-Simulator.Windows.Interface的位置，而不是exe的位置（看下面图）
4. 如果将mklink.bat改成复制到libraries下，而不是根目录，一切都运行正常，这也验证了上面说的



因此有两个解决方案：
1. 使用NetBeauty2时在配置中加入忽略移动VPet-Simulator.Core.dll、VPet-Simulator.Windows.Interface.dll，无需修改 VPet 代码
```xml
<BeautyExcludes>VPet-Simulator.Core.dll;VPet-Simulator.Windows.Interface.dll</BeautyExcludes>
```
2. VPet 考虑将`VPet-Simulator.Windows.Interface`中`ExtensionValue.BaseDirectory`优化，改为从exe位置加载，而不是当前程序集的位置加载，代码位置：https://github.com/LorisYounger/VPet/blob/5d401f0faed9542636ca919b628379d3cf4528f9/VPet-Simulator.Windows.Interface/ExtensionFunction.cs#L238-L244
![image](https://github.com/user-attachments/assets/0ee054a9-cc62-4b5b-a6d6-3645295a5cdc)


两个解决方案均能使VPet运行正常

![image](https://github.com/user-attachments/assets/c393e147-216c-4d72-8546-6f6a8b3d30fe)
